// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRTDPicjNLunskkGIz5dLx-TDzH9ZoJI',
    appId: '1:886745874317:web:3941f06dad4e120b6f07c4',
    messagingSenderId: '886745874317',
    projectId: 'ilmastoinninohjaus',
    authDomain: 'ilmastoinninohjaus.firebaseapp.com',
    databaseURL: 'https://ilmastoinninohjaus-default-rtdb.firebaseio.com',
    storageBucket: 'ilmastoinninohjaus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgZaaM1BoMk9ASiWHMzGzMyhdF9UpMK88',
    appId: '1:886745874317:android:13728d5176fa75b26f07c4',
    messagingSenderId: '886745874317',
    projectId: 'ilmastoinninohjaus',
    databaseURL: 'https://ilmastoinninohjaus-default-rtdb.firebaseio.com',
    storageBucket: 'ilmastoinninohjaus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0JEJnsWdKa15XNYZcwRKwLwsh11tjb-U',
    appId: '1:886745874317:ios:f4e90c0a2407c7a96f07c4',
    messagingSenderId: '886745874317',
    projectId: 'ilmastoinninohjaus',
    databaseURL: 'https://ilmastoinninohjaus-default-rtdb.firebaseio.com',
    storageBucket: 'ilmastoinninohjaus.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0JEJnsWdKa15XNYZcwRKwLwsh11tjb-U',
    appId: '1:886745874317:ios:f4e90c0a2407c7a96f07c4',
    messagingSenderId: '886745874317',
    projectId: 'ilmastoinninohjaus',
    databaseURL: 'https://ilmastoinninohjaus-default-rtdb.firebaseio.com',
    storageBucket: 'ilmastoinninohjaus.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtRTDPicjNLunskkGIz5dLx-TDzH9ZoJI',
    appId: '1:886745874317:web:d05bfafc6637f70c6f07c4',
    messagingSenderId: '886745874317',
    projectId: 'ilmastoinninohjaus',
    authDomain: 'ilmastoinninohjaus.firebaseapp.com',
    databaseURL: 'https://ilmastoinninohjaus-default-rtdb.firebaseio.com',
    storageBucket: 'ilmastoinninohjaus.firebasestorage.app',
  );
}
